"""update Priority table adding feasible budget

Revision ID: 09ecf4ceca27
Revises: 415315ce1b4f
Create Date: 2025-11-05 19:30:25.713208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ecf4ceca27'
down_revision: Union[str, Sequence[str], None] = '415315ce1b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('feasible_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priorities', 'feasible_budget')
    # ### end Alembic commands ###
