"""adding react_count

Revision ID: 200d570b5ee5
Revises: 3c0b0e55eeb3
Create Date: 2025-11-06 00:30:52.232241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200d570b5ee5'
down_revision: Union[str, Sequence[str], None] = '3c0b0e55eeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reacts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reacts_count')
    # ### end Alembic commands ###
