"""adding columns to blog

Revision ID: 3c0b0e55eeb3
Revises: 21da62ea9640
Create Date: 2025-11-05 23:29:55.043002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0b0e55eeb3'
down_revision: Union[str, Sequence[str], None] = '21da62ea9640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('share_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('reacts_count', sa.Integer(), nullable=True))
    op.drop_column('priorities', 'feasible_budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('feasible_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'reacts_count')
    op.drop_column('blogs', 'share_count')
    op.drop_column('blogs', 'comments_count')
    # ### end Alembic commands ###
