"""updating task table

Revision ID: 51e9a10b4de1
Revises: 200d570b5ee5
Create Date: 2025-11-07 19:20:03.026269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e9a10b4de1'
down_revision: Union[str, Sequence[str], None] = '200d570b5ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('tasks', 'days_remaining')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('days_remaining', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
