"""updated task

Revision ID: 87de0d7cf6d8
Revises: f99b0d41a4f3
Create Date: 2025-11-05 15:05:14.799740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87de0d7cf6d8'
down_revision: Union[str, Sequence[str], None] = 'f99b0d41a4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('days_remaining', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'scheduled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'days_remaining')
    # ### end Alembic commands ###
