"""initial tables

Revision ID: da1a503ac17c
Revises: 
Create Date: 2025-11-01 17:40:04.616374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1a503ac17c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('days_until_next_income', sa.Integer(), nullable=True),
    sa.Column('feasible_budget', sa.Float(), nullable=True),
    sa.Column('Savings_Percentage', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('Data', sa.String(), nullable=True),
    sa.Column('time_of_budgetting', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Expense_id'), 'Expense', ['id'], unique=False)
    op.create_index(op.f('ix_Expense_username'), 'Expense', ['username'], unique=False)
    op.create_table('Priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('essentials', sa.Float(), nullable=True),
    sa.Column('extras', sa.Float(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Priority_id'), 'Priority', ['id'], unique=False)
    op.create_index(op.f('ix_Priority_username'), 'Priority', ['username'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('author_x', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('time_of_post', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index(op.f('ix_blogs_username'), 'blogs', ['username'], unique=False)
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mathematician', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('numbers', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('time_of_calculation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    op.create_index(op.f('ix_calculations_mathematician'), 'calculations', ['mathematician'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('developer_name', sa.String(), nullable=True),
    sa.Column('passwoord', sa.String(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('trade', sa.String(), nullable=True),
    sa.Column('traders', sa.Integer(), nullable=True),
    sa.Column('sales_per_day', sa.Float(), nullable=True),
    sa.Column('taxes', sa.String(), nullable=True),
    sa.Column('union', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('time_of_commencement', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_developer_name'), 'markets', ['developer_name'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('time_of_execution', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_username'), 'tasks', ['username'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('time_of_post', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_username'), 'comments', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_username'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tasks_username'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_developer_name'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_calculations_mathematician'), table_name='calculations')
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_blogs_username'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_Priority_username'), table_name='Priority')
    op.drop_index(op.f('ix_Priority_id'), table_name='Priority')
    op.drop_table('Priority')
    op.drop_index(op.f('ix_Expense_username'), table_name='Expense')
    op.drop_index(op.f('ix_Expense_id'), table_name='Expense')
    op.drop_table('Expense')
    # ### end Alembic commands ###
