"""updated Task

Revision ID: f99b0d41a4f3
Revises: fc76e74ea33d
Create Date: 2025-11-05 14:39:03.607749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f99b0d41a4f3'
down_revision: Union[str, Sequence[str], None] = 'fc76e74ea33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('days_to_execution', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('day_of_execution', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('time_of_implementation', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'time_of_execution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_of_execution', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'time_of_implementation')
    op.drop_column('tasks', 'scheduled_at')
    op.drop_column('tasks', 'day_of_execution')
    op.drop_column('tasks', 'days_to_execution')
    # ### end Alembic commands ###
