"""upgraded tables

Revision ID: fc76e74ea33d
Revises: da1a503ac17c
Create Date: 2025-11-04 18:53:34.702464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc76e74ea33d'
down_revision: Union[str, Sequence[str], None] = 'da1a503ac17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('days_until_next_income', sa.Integer(), nullable=True),
    sa.Column('feasible_budget', sa.Float(), nullable=True),
    sa.Column('savings_percentage', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('time_of_budgetting', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essentials', sa.Float(), nullable=True),
    sa.Column('extras', sa.Float(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priorities_id'), 'priorities', ['id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('love', 'angry', 'laugh', 'wow', 'sad', name='sharetype'), nullable=True),
    sa.Column('time_of_share', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_id'), 'shares', ['id'], unique=False)
    op.create_table('reacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'love', 'angry', 'laugh', 'wow', 'sad', name='reactiontype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('time_of_reaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='unique_blog_react'),
    sa.UniqueConstraint('user_id', 'comment_id', name='unique_comment_react')
    )
    op.create_index(op.f('ix_reacts_id'), 'reacts', ['id'], unique=False)
    op.drop_index(op.f('ix_Expense_id'), table_name='Expense')
    op.drop_index(op.f('ix_Expense_username'), table_name='Expense')
    op.drop_table('Expense')
    op.drop_index(op.f('ix_Priority_id'), table_name='Priority')
    op.drop_index(op.f('ix_Priority_username'), table_name='Priority')
    op.drop_table('Priority')
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_blogs_username'), table_name='blogs')
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.drop_column('blogs', 'email')
    op.drop_column('blogs', 'username')
    op.drop_column('blogs', 'author_x')
    op.drop_column('blogs', 'nationality')
    op.drop_column('blogs', 'password')
    op.add_column('calculations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_calculations_mathematician'), table_name='calculations')
    op.create_foreign_key(None, 'calculations', 'users', ['user_id'], ['id'])
    op.drop_column('calculations', 'mathematician')
    op.drop_column('calculations', 'nationality')
    op.drop_column('calculations', 'email')
    op.drop_column('calculations', 'password')
    op.add_column('comments', sa.Column('like', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_comments_username'), table_name='comments')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'nationality')
    op.drop_column('comments', 'email')
    op.drop_column('comments', 'username')
    op.drop_column('comments', 'password')
    op.add_column('markets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_markets_developer_name'), table_name='markets')
    op.create_foreign_key(None, 'markets', 'users', ['user_id'], ['id'])
    op.drop_column('markets', 'developer_name')
    op.drop_column('markets', 'passwoord')
    op.drop_column('markets', 'nationality')
    op.drop_column('markets', 'email')
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_tasks_username'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'nationality')
    op.drop_column('tasks', 'email')
    op.drop_column('tasks', 'username')
    op.drop_column('tasks', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_username'), 'tasks', ['username'], unique=False)
    op.drop_column('tasks', 'user_id')
    op.add_column('markets', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markets', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markets', sa.Column('passwoord', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markets', sa.Column('developer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'markets', type_='foreignkey')
    op.create_index(op.f('ix_markets_developer_name'), 'markets', ['developer_name'], unique=False)
    op.drop_column('markets', 'user_id')
    op.add_column('comments', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_index(op.f('ix_comments_username'), 'comments', ['username'], unique=False)
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'like')
    op.add_column('calculations', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('calculations', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('calculations', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('calculations', sa.Column('mathematician', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calculations', type_='foreignkey')
    op.create_index(op.f('ix_calculations_mathematician'), 'calculations', ['mathematician'], unique=False)
    op.drop_column('calculations', 'user_id')
    op.add_column('blogs', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('author_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_index(op.f('ix_blogs_username'), 'blogs', ['username'], unique=False)
    op.drop_column('blogs', 'user_id')
    op.create_table('Priority',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('essentials', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extras', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Priority_pkey'))
    )
    op.create_index(op.f('ix_Priority_username'), 'Priority', ['username'], unique=False)
    op.create_index(op.f('ix_Priority_id'), 'Priority', ['id'], unique=False)
    op.create_table('Expense',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('days_until_next_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feasible_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Savings_Percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_of_budgetting', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Expense_pkey'))
    )
    op.create_index(op.f('ix_Expense_username'), 'Expense', ['username'], unique=False)
    op.create_index(op.f('ix_Expense_id'), 'Expense', ['id'], unique=False)
    op.drop_index(op.f('ix_reacts_id'), table_name='reacts')
    op.drop_table('reacts')
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_priorities_id'), table_name='priorities')
    op.drop_table('priorities')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
